### ISSUE TITLE
Run the OLED Mono using I2C instead of SPI

### ISSUE THREAD

**Issue by sofian** [a3lab/xenolalia#20]

**Comment by sofian** [comment]
In the process I believe we fried our device. Ordering an alternative i2c screen.

**Comment by sofian** [comment]
We had many problems with this. See the following discussion about running it from a RPi:
https://github.com/rm-hull/luma.oled/issues/276

**Comment by tezgit** [comment]
I have been running two different I2C scanner sketches on Arduino Nano and on ESP32 with no success in detecting an address for the 128x128 I2C (only) display >> https://www.tinytronics.nl/shop/en/display/oled/1.5-inch-oled-display-128*128-pixels-white-i2c

After trying various HW I2C constructors with the U8g2lib I finally decided to give the SW I2C a try and managed to get the screen to work and run the page-buffer GraphicTest with this definition for 96x96 pixels 

U8G2_SSD1327_SEEED_96X96_1_SW_I2C u8g2(U8G2_R0, /* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);  // Seeedstudio Grove OLED 96x96

![SD1327-96px](https://user-images.githubusercontent.com/15217963/75767177-a541d080-5d42-11ea-9103-42e443ad610f.jpg)

This one actually worked too but the sketch seems to stop after displaying the first screen in full 128 x 128 resolution

U8G2_SSD1327_EA_W128128_1_SW_I2C u8g2(U8G2_R0, /* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);

![SD1327-128px](https://user-images.githubusercontent.com/15217963/75767625-69f3d180-5d43-11ea-8998-0b0f8563ce2d.jpg)

and this is the backside of the display board

<img width="359" alt="SD1327-I2C-back" src="https://user-images.githubusercontent.com/15217963/75767851-be974c80-5d43-11ea-9b05-a9b455af1346.png">

**Comment by sofian** [comment]
Because of all the difficulties explained here we are falling back to work in SPI.
