### ISSUE TITLE
The black round 3d printed mask seems incomplete

### ISSUE THREAD

**Issue by sofian** [a3lab/xenolalia#63]
The black 3d printed round mask seems to not entirely cover the sides of the screen, hence it does not appear truly "round". Perhaps we should adjust its positioning on the screen and/or make it a bit wider.

Look at the bottom of the image here you can see it quite clearly.

![image](https://user-images.githubusercontent.com/791244/133346293-6fafc746-8c05-4806-a735-19369bf94e99.png)

**Comment by etiennemontenegro** [comment]
Is this with the new part i uploaded yesterday? I'll make a new version with a larger outer diameter tomorrow morning.

**Comment by etiennemontenegro** [comment]
I just added a 62MM and 63MM version to the drive so you can print both and test

**Comment by sofian** [comment]
Ok but I feel it is not the outer diameter but rather the inner diameter which should be adjusted. I can take measurements today and send them to you.
